### PR TITLE
Enable HttpService when building

### PR DESCRIPTION
**Pull request by catgirlinspace**
If HttpService was disabled before the command is ran, it will enable HttpService and then disable it afterwards.

### CODE REVIEW

**Comment by MrSprinkleToes** [comment]
https://devforum.roblox.com/t/allow-studio-plugins-to-request-http-service-access-without-enabling-http-service-for-the-entire-game/333348 Looks like something for this may be in the works, when someone updates me about the status of that feature I'll decide what to do here. Thanks for reminding me about this!

**Comment by MrSprinkleToes** [comment]
Nevermind, looks like this feature did become a thing! Will be implementing HTTP permissions for the plugin soon.

**Comment by lavender-sys** [comment]
This isn't related to the actual plugin, this is related to building the plugin.

**Comment by MrSprinkleToes** [comment]
Yes, but I can make it so the plugin has permission to use HTTP requests even if HTTP is disabled. The user just needs to press a button on a window that pops up.

**Comment by lavender-sys** [comment]
Building the plugin involves running a script in the command bar. Accessing HttpService within the command bar does not work the same as a plugin and requires HttpService to be enabled, unlike plugins where a modal appears.

**Pull request closed without merging**
